### ISSUE TITLE
Error when running "upgrade remnux"

### ISSUE THREAD

**Issue by J0xA0** [REMnux/remnux-cli#50]
I've been having this error when running remnux upgrade:

````
>> Running: ssh  
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit `(internal/child_process.js:286:5)
````
Adding the log file for more detail
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7366641/saltstack.log)

Can you please check?

**Comment by lennyzeltser** [comment]
I believe the error is tied to a certificate problem with the Node.js rep, which we addressed recently. I believe when you ran `remnux upgrade`, your system received that fix, so in the future you shouldn't be affected by that issue.  One way to confirm this now is to run `remnux update`, which should complete now without errors.

**Comment by J0xA0** [comment]
@lennyzeltser, unfortunately running `remnux update` does not solve the problem as the error also shows up

``` >> Running: away-from-the-dog

>> Running: echo "wireshark-common wireshark-common/install-setuid select True"| debconf-set-selections; dpkg-reconfigure -f noninteractive wireshark-common
>> Running: wireshark
>> Running: remnux-theme
>> Running: ssh
Update returned exit code not zero
Error: Update returned exit code not zero
    at ChildProcess.<anonymous> (/snapshot/remnux-cli/remnux-cli.js:569:23)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
```

However, I've noticed something that might be important.
When I run `remnux upgrade`, the version downloaded is **v2021.41.1** while when I run `remnux update`, the version is **v2021.32.3**

```
remnux@remnux:~$ remnux update
> remnux-cli@1.3.3.0.g1df38b1
> remnux-version: v2021.32.3
 
> downloading v2021.32.3
>> downloading remnux-salt-states-v2021.32.3.tar.gz.asc
>> downloading remnux-salt-states-v2021.32.3.tar.gz.sha256
>> downloading remnux-salt-states-v2021.32.3.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2021.32.3.tar.gz
> validating file remnux-salt-states-v2021.32.3.tar.gz
> validating signature for remnux-salt-states-v2021.32.3.tar.gz.sha256
> extracting update remnux-salt-states-v2021.32.3.tar.gz
> using previous mode: dedicated
> upgrading/updating to v2021.32.3
>> Log file: /var/cache/remnux/cli/v2021.32.3/saltstack.log
```

```
remnux@remnux:~$ remnux upgrade
> remnux-cli@1.3.3.0.g1df38b1
> remnux-version: v2021.32.3
 
> downloading v2021.41.1
>> downloading remnux-salt-states-v2021.41.1.tar.gz.asc
>> downloading remnux-salt-states-v2021.41.1.tar.gz.sha256
>> downloading remnux-salt-states-v2021.41.1.tar.gz.sha256.asc
>> downloading remnux-salt-states-v2021.41.1.tar.gz
> validating file remnux-salt-states-v2021.41.1.tar.gz
> validating signature for remnux-salt-states-v2021.41.1.tar.gz.sha256
> extracting update remnux-salt-states-v2021.41.1.tar.gz
> using previous mode: dedicated
> upgrading/updating to v2021.41.1
>> Log file: /var/cache/remnux/cli/v2021.41.1/saltstack.log

```

I've attached the `saltstack.log` file originated from running the command `remnux update`. 
[saltstack.log](https://github.com/REMnux/remnux-cli/files/7368186/saltstack.log)

**Comment by lennyzeltser** [comment]
Thanks for the extra details! Could you please confirm that you first ran `remnux upgrade` and only afterwards ran `remnux update`?

**Comment by J0xA0** [comment]
That is normally the order that I run it, yes.

**Comment by J0xA0** [comment]
@lennyzeltser , any updates on this?
I just decided to import the remnux-v7-focal.ova to have a new VM with REMnux. After importing, the first command that I've  executed was `remnux upgrade` and I had the same problem.

**Comment by lennyzeltser** [comment]
Thanks for following up, @J0xA0! Would you be able to share the saltstack.log file from the new VM?

**Comment by J0xA0** [comment]
@lennyzeltser, as requested:

[saltstack.log](https://github.com/REMnux/remnux-cli/files/7462215/saltstack.log)

**Comment by lennyzeltser** [comment]
Looks like the issue was with upgrading NetworkMiner. This is because they released a new version of the tool today, so the hash value expected by the REMnux installer didn't match. I'll get this addressed soon.

Everything else was set up just fine.

**Comment by Evan-Sa** [comment]
Was experiencing the same issue as the original poster but I just checked and remnux upgrade is now working without errors. Thank you for getting the network miner issue fixed so quickly, 

Have a safe day,

**Comment by lennyzeltser** [comment]
Indeed, REMnux will now grab the latest version of NetworkMiner. Looks to be working from my side, too.

**Comment by J0xA0** [comment]
Thank you for the update @lennyzeltser 

I can confirm that in the VM that I installed yesterday, it's working however the one I reported initially which I use daily is still breaking at the same line and reinstalling it would bring me lots of work so I would really like to avoid it.

Is there any other way for me to debug the problem or disable the specifc line that is breaking so I can update the rest of the VM?

**Comment by lennyzeltser** [comment]
@J0xA0, the issue in the saltstack.log that you originally uploaded is with the configuration of APT repo sources, as far as I can tell.

The problem was triggered by the NodeJS repo certificate expiring. We [adjusted REMnux](https://github.com/REMnux/salt-states/commit/01eebfcc0a2cfd68f9ec0f75eb1ed8bb579094c3#diff-65b367a095591db653b18e35f75c4fc66e73e03d8fe6f08777c55bf5468194e3) to use the HTTP version of their site (since packages are signed anyway without issues). 

For some reason, your APT configuration is still producing an error when you try to refresh packages. I think the problem is triggered when refreshing the Sublime Text repo, which you added to your VM. To diagnose the issue on that VM, look to tweak the files in your `etc/apt/sources.list.d` directory and see if you can get `apt-get update` to complete without errors.

**Comment by J0xA0** [comment]
Hello @lennyzeltser 

That's what I did after my comment and I also compared some of the apt repos with the fresh instalation of REMnux and manually changed one repo to HTTP.

Now everything is working well. 

Thank you for your help.

**Comment by Ch4kr4k** [comment]
@J0xA0 
Hello sir , would you mind telling me which repos did you change

**Comment by J0xA0** [comment]
> @J0xA0 Hello sir , would you mind telling me which repos did you change

Sorry but I don't remember anymore which one I changed. But if you are facing the same problem, then install a new version of REMnux and compare the apt repos with the ones you have  and you will spot the one you need to change.

**Comment by Ch4kr4k** [comment]
@J0xA0 thanks it was a bug in saltstacks

**Comment by wabass** [comment]
@lennyzeltser,
Tried to use it on Ubuntu-Jammy (Ubuntu Pro). This way it will be on the latest OS. But return like this. Perhaps its only good for focal?

![image](https://user-images.githubusercontent.com/109649776/231695777-9e15c969-e607-4816-986f-64889da508f6.png)

**Comment by Ch4kr4k** [comment]
Solved the issue by replacing /usr/bin/remnux with the downloaded remnux cli tool from the official website and upgrading the ssh with apt and running remnux upgrade

**Comment by wabass** [comment]
> 

You mean by this "https://REMnux.org/remnux-cli" ?
I tried it many times. Still same error. In fact, that screenshot is from the official website.

OR

By this one "https://github.com/REMnux/remnux-cli.git" ?

**Comment by Ch4kr4k** [comment]
https://REMnux.org/remnux-cli 
This one
Try removing the remnux cache in var lib
Looks like the version that you are using is incomparable sir
And you did not run it with sudo 
I haven't tried it on the newer Ubuntu
Just install all the tools there is in remnux on the one you are using

**Comment by wabass** [comment]
> https://REMnux.org/remnux-cli This one Try removing the remnux cache in var lib Looks like the version that you are using is incomparable sir

Exactly what I say "Tried to use it on Ubuntu-Jammy (Ubuntu Pro"

Alright gonna try it.

EDIT:

Nadah!.. its good for Focal version only.

**Comment by Ch4kr4k** [comment]
> > https://REMnux.org/remnux-cli This one Try removing the remnux cache in var lib Looks like the version that you are using is incomparable sir
> 
> Exactly what I say "Tried to use it on Ubuntu-Jammy (Ubuntu Pro"
> 
> Alright gonna try it.
> 

All the best hope you succeed it
